import {
  Bell,
  Camera,
  ClipboardList,
  Command,
  Crosshair,
  Gauge,
  History,
  KeyRound,
  MapPinned,
  MonitorSmartphone,
  RadioTower,
  Route,
  ShieldCheck,
  UserRoundCog,
} from "lucide-react";

export type FieldType = "text" | "number" | "datetime-local" | "textarea" | "select";

export type ApiField = {
  key: string;
  label: string;
  type?: FieldType;
  placeholder?: string;
  required?: boolean;
  options?: { label: string; value: string }[];
  hint?: string;
};

export type ApiMethod = {
  method: string;
  title: string;
  group: string;
  icon: typeof MonitorSmartphone;
  description: string;
  fields: ApiField[];
};

export const methodCatalog: ApiMethod[] = [
  {
    method: "jimi.oauth.token.get",
    title: "Access token",
    group: "Authentication",
    icon: KeyRound,
    description: "Creates the account access token used by every protected request.",
    fields: [],
  },
  {
    method: "jimi.user.child.list",
    title: "Sub accounts",
    group: "Account",
    icon: UserRoundCog,
    description: "Fetch sub-users and account hierarchy for the configured tenant.",
    fields: [{ key: "target", label: "Account" }],
  },
  {
    method: "jimi.user.device.list",
    title: "Device list",
    group: "Fleet",
    icon: MonitorSmartphone,
    description: "List vehicles/devices bound to the current account.",
    fields: [
      { key: "target", label: "Account" },
    ],
  },
  {
    method: "jimi.track.device.detail",
    title: "Device detail",
    group: "Fleet",
    icon: MonitorSmartphone,
    description: "Get detailed terminal, vehicle, SIM, driver, and platform information.",
    fields: [{ key: "imei", label: "IMEI", required: true }],
  },
  {
    method: "jimi.user.device.expiration.update",
    title: "Update expiration",
    group: "Fleet",
    icon: MonitorSmartphone,
    description: "Update the platform expiration date for a user/device relationship.",
    fields: [
      { key: "target", label: "Account", required: true },
      { key: "imei", label: "IMEI", required: true },
      { key: "expiration", label: "Expiration", placeholder: "yyyy-MM-dd HH:mm:ss", required: true },
    ],
  },
  {
    method: "jimi.open.device.update",
    title: "Update vehicle",
    group: "Fleet",
    icon: MonitorSmartphone,
    description: "Edit vehicle profile fields by IMEI.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "vehicle_name", label: "Vehicle name" },
      { key: "vehicle_number", label: "Plate number" },
      { key: "driver_name", label: "Driver name" },
      { key: "driver_phone", label: "Driver phone" },
    ],
  },
  {
    method: "jimi.open.device.move",
    title: "Move devices",
    group: "Fleet",
    icon: MonitorSmartphone,
    description: "Move devices between accounts.",
    fields: [
      { key: "imeis", label: "IMEI list", required: true },
      { key: "target_account", label: "Target account", required: true },
    ],
  },
  {
    method: "jimi.open.device.bind",
    title: "Bind app user",
    group: "Fleet",
    icon: UserRoundCog,
    description: "Bind devices to an app user.",
    fields: [
      { key: "account", label: "App user", required: true },
      { key: "imeis", label: "IMEI list", required: true },
    ],
  },
  {
    method: "jimi.open.device.unbind",
    title: "Unbind app user",
    group: "Fleet",
    icon: UserRoundCog,
    description: "Remove an app-user/device binding.",
    fields: [
      { key: "account", label: "App user", required: true },
      { key: "imeis", label: "IMEI list", required: true },
    ],
  },
  {
    method: "jimi.device.group.create",
    title: "Create group",
    group: "Fleet",
    icon: ClipboardList,
    description: "Create a device group under an account.",
    fields: [
      { key: "target", label: "Account", required: true },
      { key: "group_name", label: "Group name", required: true },
    ],
  },
  {
    method: "jimi.device.group.update",
    title: "Update group",
    group: "Fleet",
    icon: ClipboardList,
    description: "Edit a device group name or membership.",
    fields: [
      { key: "group_id", label: "Group ID", required: true },
      { key: "group_name", label: "Group name", required: true },
    ],
  },
  {
    method: "jimi.device.group.delete",
    title: "Delete group",
    group: "Fleet",
    icon: ClipboardList,
    description: "Delete a device group.",
    fields: [{ key: "group_id", label: "Group ID", required: true }],
  },
  {
    method: "jimi.device.group.list",
    title: "Group list",
    group: "Fleet",
    icon: ClipboardList,
    description: "Get the device groups of an account.",
    fields: [{ key: "target", label: "Account" }],
  },
  {
    method: "jimi.user.device.location.list",
    title: "Account locations",
    group: "Live tracking",
    icon: MapPinned,
    description: "Get latest location of all devices under an account.",
    fields: [{ key: "target", label: "Account", required: true }],
  },
  {
    method: "jimi.device.location.get",
    title: "Latest location",
    group: "Live tracking",
    icon: MapPinned,
    description: "Read current GPS status, address-ready coordinates, speed, course, and online state.",
    fields: [{ key: "imeis", label: "IMEI list", required: true, placeholder: "IMEI1,IMEI2" }],
  },
  {
    method: "jimi.device.location.URL.share",
    title: "Share location URL",
    group: "Live tracking",
    icon: MapPinned,
    description: "Generate a shareable location page URL for a device.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "expires_in", label: "Expires in seconds", type: "number", placeholder: "3600" },
    ],
  },
  {
    method: "jimi.device.track.mileage",
    title: "Track mileage",
    group: "Live tracking",
    icon: Gauge,
    description: "Get mileage data for one or more devices.",
    fields: [
      { key: "imeis", label: "IMEI list", required: true },
      { key: "begin_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.device.track.list",
    title: "Historical track",
    group: "Live tracking",
    icon: Route,
    description: "Query playback points between two UTC/local time boundaries.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "begin_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.lbs.address.get",
    title: "LBS address",
    group: "Live tracking",
    icon: RadioTower,
    description: "Resolve Wi-Fi/base-station location information.",
    fields: [{ key: "lbs", label: "LBS payload", type: "textarea", required: true }],
  },
  {
    method: "jimi.open.platform.report.parking",
    title: "Parking report",
    group: "Reports",
    icon: Gauge,
    description: "Get parking and idling data for devices.",
    fields: [
      { key: "imeis", label: "IMEI list", required: true },
      { key: "start_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.device.location.getTagMsg",
    title: "TAG location",
    group: "Live tracking",
    icon: MapPinned,
    description: "Get the latest location message for a TAG device.",
    fields: [{ key: "imei", label: "IMEI", required: true }],
  },
  {
    method: "jimi.device.live.page.url",
    title: "Live stream page",
    group: "Video and media",
    icon: Camera,
    description: "Get the web page URL for supported live streaming devices.",
    fields: [{ key: "imei", label: "IMEI", required: true }],
  },
  {
    method: "jimi.device.meida.cmd.send",
    title: "Send media command",
    group: "Video and media",
    icon: Camera,
    description: "Send a photo/video capture instruction to a media-capable device.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "cmd", label: "Command", required: true },
      { key: "param", label: "Parameters", type: "textarea" },
    ],
  },
  {
    method: "jimi.device.history.cmd.send",
    title: "History video command",
    group: "Video and media",
    icon: Camera,
    description: "Request historical video from supported devices.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "start_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.device.jimi.media.URL",
    title: "Photo/video URL",
    group: "Video and media",
    icon: Camera,
    description: "Get a JIMI device photo or video URL.",
    fields: [{ key: "file_id", label: "File ID", required: true }],
  },
  {
    method: "jimi.device.media.event.URL",
    title: "Media event URL",
    group: "Video and media",
    icon: Camera,
    description: "Get the URL for a media event.",
    fields: [{ key: "event_id", label: "Event ID", required: true }],
  },
  {
    method: "jimi.open.instruction.list",
    title: "Supported commands",
    group: "Remote control",
    icon: Command,
    description: "Get the command list supported by a device.",
    fields: [{ key: "imei", label: "IMEI", required: true }],
  },
  {
    method: "jimi.open.instruction.send",
    title: "Send instruction",
    group: "Remote control",
    icon: Command,
    description: "Send a supported platform instruction to a device.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "instruction", label: "Instruction", required: true },
      { key: "params", label: "Parameters", type: "textarea" },
    ],
  },
  {
    method: "jimi.open.instruction.result",
    title: "Instruction result",
    group: "Remote control",
    icon: ClipboardList,
    description: "Get command execution results.",
    fields: [{ key: "cmd_id", label: "Command ID", required: true }],
  },
  {
    method: "jimi.open.instruction.raw.send",
    title: "Send raw command",
    group: "Remote control",
    icon: Command,
    description: "Send raw command data to a device.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "content", label: "Raw content", type: "textarea", required: true },
    ],
  },
  {
    method: "jimi.device.alarm.list",
    title: "Alarm history",
    group: "Safety",
    icon: Bell,
    description: "Query overspeed, vibration, power, SOS, geo, and platform alarms.",
    fields: [
      { key: "imei", label: "IMEI", placeholder: "Optional single device" },
      { key: "begin_time", label: "Start", type: "datetime-local" },
      { key: "end_time", label: "End", type: "datetime-local" },
      { key: "alarm_type", label: "Alarm type", placeholder: "Optional" },
      { key: "page_no", label: "Page", type: "number", placeholder: "1" },
      { key: "page_size", label: "Page size", type: "number", placeholder: "100" },
    ],
  },
  {
    method: "jimi.open.device.fence.create",
    title: "Create device fence",
    group: "Geofence",
    icon: ShieldCheck,
    description: "Create a Geo-fence directly for an IMEI.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "fence_name", label: "Fence name", required: true },
      { key: "fence_data", label: "Fence data", type: "textarea", required: true },
    ],
  },
  {
    method: "jimi.open.device.fence.delete",
    title: "Delete device fence",
    group: "Geofence",
    icon: ShieldCheck,
    description: "Delete a Geo-fence from a device.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "fence_id", label: "Fence ID", required: true },
    ],
  },
  {
    method: "jimi.open.platform.fence.create",
    title: "Create/edit platform fence",
    group: "Geofence",
    icon: Crosshair,
    description: "Create or edit a reusable platform Geo-fence.",
    fields: [
      { key: "target", label: "Account" },
      { key: "fence_id", label: "Fence ID", placeholder: "Only when editing" },
      { key: "fence_name", label: "Fence name", required: true },
      { key: "fence_data", label: "Fence data", type: "textarea", required: true },
    ],
  },
  {
    method: "jimi.open.platform.fence.delete",
    title: "Delete platform fence",
    group: "Geofence",
    icon: ShieldCheck,
    description: "Delete a platform Geo-fence.",
    fields: [{ key: "fence_id", label: "Fence ID", required: true }],
  },
  {
    method: "jimi.open.platform.fence.bind",
    title: "Bind platform fence",
    group: "Geofence",
    icon: Crosshair,
    description: "Associate a platform Geo-fence with devices.",
    fields: [
      { key: "fence_id", label: "Fence ID", required: true },
      { key: "imeis", label: "IMEI list", required: true },
    ],
  },
  {
    method: "jimi.open.platform.fence.list",
    title: "Platform fence list",
    group: "Geofence",
    icon: ShieldCheck,
    description: "List platform Geo-fences for an account.",
    fields: [{ key: "target", label: "Account" }],
  },
  {
    method: "jimi.open.platform.fence.detail",
    title: "Fence detail",
    group: "Geofence",
    icon: ShieldCheck,
    description: "Query one platform Geo-fence.",
    fields: [{ key: "fence_id", label: "Fence ID", required: true }],
  },
  {
    method: "jimi.device.obd.list",
    title: "OBD data",
    group: "Diagnostics",
    icon: History,
    description: "Fetch OBD telemetry for compatible hardware.",
    fields: [
      { key: "imei", label: "IMEI", required: true },
      { key: "start_time", label: "Start", type: "datetime-local" },
      { key: "end_time", label: "End", type: "datetime-local" },
    ],
  },
  {
    method: "jimi.device.obd.fault",
    title: "OBD fault data",
    group: "Diagnostics",
    icon: History,
    description: "Fetch OBD fault codes for compatible hardware.",
    fields: [{ key: "imei", label: "IMEI", required: true }],
  },
  {
    method: "jimi.open.platform.fence.duration",
    title: "Fence duration",
    group: "Reports",
    icon: ShieldCheck,
    description: "Get entry and exit fence duration data for devices.",
    fields: [
      { key: "imeis", label: "IMEI list", required: true },
      { key: "start_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.open.platform.report.trips",
    title: "Trips report",
    group: "Reports",
    icon: Route,
    description: "Get trip report data for devices.",
    fields: [
      { key: "imeis", label: "IMEI list", required: true },
      { key: "start_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
    ],
  },
  {
    method: "jimi.open.device.rfid.list",
    title: "RFID report",
    group: "Reports",
    icon: ClipboardList,
    description: "Get RFID reporting information.",
    fields: [
      { key: "imei", label: "IMEI" },
      { key: "start_time", label: "Start", type: "datetime-local" },
      { key: "end_time", label: "End", type: "datetime-local" },
    ],
  },
  {
    method: "jimi.open.platform.dlt.report",
    title: "DLT report",
    group: "Reports",
    icon: ClipboardList,
    description: "Retrieve DLT card and operation report information.",
    fields: [
      { key: "start_time", label: "Start", type: "datetime-local", required: true },
      { key: "end_time", label: "End", type: "datetime-local", required: true },
      { key: "imei", label: "IMEI" },
      { key: "dlt", label: "DLT card" },
    ],
  },
  {
    method: "jimi.push.device.alarm",
    title: "Alarm push payload",
    group: "Push",
    icon: Bell,
    description: "Endpoint contract for receiving alarm push notifications.",
    fields: [{ key: "payload", label: "Push payload", type: "textarea" }],
  },
  {
    method: "jimi.open.instruction.raw.receive",
    title: "Raw data push",
    group: "Push",
    icon: RadioTower,
    description: "Endpoint contract for receiving raw device data.",
    fields: [{ key: "payload", label: "Push payload", type: "textarea" }],
  },
  {
    method: "jimi.user.child.create",
    title: "Create sub-account",
    group: "Account",
    icon: UserRoundCog,
    description: "Create a distributor, end-user, or sales sub-account.",
    fields: [
      { key: "super_account", label: "Parent account" },
      { key: "account_id", label: "Account ID", required: true },
      { key: "nick_name", label: "Nick name", required: true },
      { key: "account_type", label: "Account type", required: true },
      { key: "password", label: "Password MD5", required: true },
      { key: "Email", label: "Email", required: true },
      { key: "permissions", label: "Permissions", placeholder: "111000", required: true },
    ],
  },
  {
    method: "jimi.user.child.del",
    title: "Remove sub-account",
    group: "Account",
    icon: UserRoundCog,
    description: "Remove a sub-account.",
    fields: [
      { key: "super_account", label: "Parent account" },
      { key: "account_id", label: "Account ID", required: true },
    ],
  },
  {
    method: "jimi.user.child.move",
    title: "Move account",
    group: "Account",
    icon: UserRoundCog,
    description: "Move an account under another sub-account.",
    fields: [
      { key: "account", label: "Account", required: true },
      { key: "target_account", label: "Target account", required: true },
    ],
  },
  {
    method: "jimi.user.child.update",
    title: "Edit user information",
    group: "Account",
    icon: UserRoundCog,
    description: "Update user profile and permissions.",
    fields: [
      { key: "edit_account", label: "Account", required: true },
      { key: "nick_name", label: "Nick name", required: true },
      { key: "Email", label: "Email", required: true },
      { key: "permissions", label: "Permissions", required: true },
    ],
  },
];

export const methodGroups = Array.from(new Set(methodCatalog.map((item) => item.group)));
